# AI Web IDE Docker Compose 配置
# 管理前端、後端、CI Runner 等多個容器服務

version: '3.8'

services:
  # 前端 AI Web IDE 服務
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ai-web-ide-frontend
    ports:
      - "3000:3000"
    volumes:
      # 映射源代碼目錄以支援熱重載
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./next.config.ts:/app/next.config.ts
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./tsconfig.json:/app/tsconfig.json
      # 排除 node_modules，使用容器內的
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true  # 支援文件監控
    networks:
      - ai-ide-network
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 後端服務 (Node.js + Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-web-ide-backend  
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      # 掛載 Docker socket 以控制容器
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - ai-ide-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis 服務 (會話管理和快取)
  redis:
    image: redis:7-alpine
    container_name: ai-web-ide-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-ide-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL 資料庫 (專案數據和歷史記錄)
  postgres:
    image: postgres:15-alpine
    container_name: ai-web-ide-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=ai_web_ide
      - POSTGRES_USER=ai_user
      - POSTGRES_PASSWORD=ai_password_2024
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    networks:
      - ai-ide-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_user -d ai_web_ide"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CI/CD Runner (用於自動部署)
  ci-runner:
    image: node:18-alpine
    container_name: ai-web-ide-ci-runner
    volumes:
      - ./ci:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - ai-ide-network
    restart: unless-stopped
    command: ["tail", "-f", "/dev/null"]  # 保持容器運行

  # Nginx 反向代理 (生產環境使用)
  nginx:
    image: nginx:alpine
    container_name: ai-web-ide-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - ai-ide-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    profiles:
      - production  # 只在生產環境啟用

# 網路配置
networks:
  ai-ide-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 資料卷配置
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  node_modules:
    driver: local

# 開發環境快速啟動配置
# 使用方式:
# 開發環境: docker-compose up -d
# 生產環境: docker-compose --profile production up -d
# 僅前端: docker-compose up frontend
# 停止所有: docker-compose down
# 清理數據: docker-compose down -v 